py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\ingolstadt\simulation\2_uam_hubs_24h_sim.sumocfg
py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\ingolstadt\simulation\3_uam_hubs_24h_sim.sumocfg
py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\ingolstadt\simulation\5_uam_hubs_24h_sim.sumocfg

REM  Ulm throws a SUMO error: date: 29.08.2024
REM  py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\Ulm\2_uam_hubs_osm.sumocfg
REM  py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\Ulm\3_uam_hubs_osm.sumocfg
REM  py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\Ulm\5_uam_hubs_osm.sumocfg

py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\London\2_uam_hubs_osm.sumocfg
py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\London\3_uam_hubs_osm.sumocfg
py uamTraCI.py --nogui --loop --uam_step_size 0.05 --uam_start_density 0.0 --uam_upper_bound 0.3 --scenario_path C:\Users\MI\PycharmProjects\sumo-uam-2024\scenarios\London\5_uam_hubs_osm.sumocfg